# _config.yml

# Site settings
title: Monstrum Wiki
description: A wiki of dark stories and characters
baseurl: "" # leave this blank for root
url: "https://yourusername.github.io" # Replace with your actual GitHub Pages URL

# Theme settings
theme: minima

# Customization for Minima Theme (Merlot-Inspired)
minima:
  skin: dark
  palette:
    primary: "#800000"  # Merlot red
    secondary: "#333333"  # Dark gray background
    accent: "#ff6347"  # Accent color (a bit lighter for contrast)

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM  # GitHub-flavored Markdown
  syntax_highlighter_opts:
    block: false

# Navigation
permalink: pretty
paginate: 5

# Include pages for navigation
include:
  - index.md
  - _stories/
  - _characters/

# Plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-sitemap
